export * from "./spell";
export * from "./lightning-spell";
export * from "./quake-spell";
export * from "./swamp-spell";
export * from "./volcano-spell";
export * from "./tornado-spell";
export * from "./blast-spell";
export * from "./armageddon-spell";
export * from "./sculpt-spell";
